name: Amber Loop
on:
  push:
    paths:
      - ".github/workflows/amber-loop.yml"
      - "requirements.txt"
      - "**/*.py"
  workflow_dispatch:

permissions:
  contents: write

env:
  APP_MODULE: server:app          # <-- change to main:app or app:app if your file differs

jobs:
  loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          # ensure these exist even if requirements.txt missed them
          pip install fastapi "uvicorn[standard]" pynacl python-dotenv || true
          sudo apt-get update && sudo apt-get install -y jq

      - name: Launch API
        env:
          APP_MODULE: ${{ env.APP_MODULE }}
        run: |
          set -Eeuo pipefail
          # 1) sanity-check import of APP_MODULE (fails fast with message)
          python - <<'PY'
          import importlib, os, sys
          mod, attr = os.environ.get('APP_MODULE','server:app').split(':',1)
          try:
              m = importlib.import_module(mod)
              app = getattr(m, attr, None)
              assert app is not None, f"{mod}:{attr} not found"
          except Exception as e:
              print(f"❌ Import failed for {mod}:{attr} -> {e}")
              sys.exit(2)
          print(f"✅ Import OK: {mod}:{attr}")
          PY

          # 2) start uvicorn and wait for /health
          nohup python -m uvicorn "$APP_MODULE" --host 127.0.0.1 --port 8787 >/tmp/app.log 2>&1 &
          for i in {1..40}; do
            if curl -sf http://127.0.0.1:8787/health >/dev/null; then
              echo "API is up"; break
            fi
            # if process died, show logs and bail
            if ! ps aux | grep -q "[u]vicorn.*8787"; then
              echo "❌ Uvicorn exited early. Recent logs:"; tail -n +1 /tmp/app.log; exit 7
            fi
            sleep 0.5
          done
          echo "---- tail /tmp/app.log ----"
          tail -n 50 /tmp/app.log || true

      - name: Amber → Eval → Label → Promote
        env: { BASE: http://127.0.0.1:8787 }
        run: |
          set -Eeuo pipefail
          echo "Capture Amber"
          AR_JSON=$(curl -sS -f "$BASE/api/amber/capture" -H 'content-type: application/json' \
            --data '{"flags":["amber:unconfirmed"],"metrics":{"unconfirmed_ratio":0.42},"digests":{"claim_graph_hash":"x"}}' | tee /tmp/ar.json)
          AR=$(jq -er '.receipt.rid' /tmp/ar.json); echo "AR=$AR"

          echo "Eval"
          EVR_JSON=$(curl -sS -f "$BASE/api/amber/eval" -H 'content-type: application/json' \
            --data "{\"parent\":\"$AR\",\"tests\":[{\"name\":\"consistency\",\"pass\":true}]}" | tee /tmp/evr.json)
          EVR=$(jq -er '.receipt.rid' /tmp/evr.json); echo "EVR=$EVR"

          echo "Label"
          LBR_JSON=$(curl -sS -f "$BASE/api/amber/label" -H 'content-type: application/json' \
            --data "{\"parent\":\"$AR\",\"label\":{\"verdict\":\"correct\",\"reason_codes\":[\"retrieval-agreement↑\"]}}" | tee /tmp/lbr.json)
          LBR=$(jq -er '.receipt.rid' /tmp/lbr.json); echo "LBR=$LBR"

          echo "Promote"
          GPR_JSON=$(curl -sS -f "$BASE/api/amber/promote" -H 'content-type: application/json' \
            --data "{\"parent\":\"$AR\",\"basis\":{\"label_ref\":\"$LBR\",\"eval_refs\":[\"$EVR\"]},\"policy_checks\":{\"pii\":\"pass\",\"consent\":\"pass\"}}" | tee /tmp/gpr.json)
          GPR=$(jq -er '.receipt.rid' /tmp/gpr.json); echo "GPR=$GPR"

      - name: Commit receipts to docs/
        if: always()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p docs/receipts/amber docs/receipts/eval docs/receipts/label docs/receipts/promote
          git add docs/receipts docs/receipt.latest.json || true
          git commit -m "chore(ci): publish latest receipt chain" || echo "nothing to commit"
          git push || true

      - name: Warn if Amber without Gold
        run: |
          AMBER=$(ls docs/receipts/amber/*.json 2>/dev/null | wc -l || true)
          GOLD=$(ls docs/receipts/promote/*.json 2>/dev/null | wc -l || true)
          echo "Amber:$AMBER Gold:$GOLD"
          if [ "$AMBER" -gt 0 ] && [ "$GOLD" -eq 0 ]; then
            echo "::warning::Amber exists; training jobs must require Gold receipts"
          fi
